### ISSUE TITLE
Migration to null safety

### ISSUE THREAD

**Issue by Cat-sushi** [yshrsmz/unorm-dart#10]

**Comment by Cat-sushi** [comment]
@espresso3389 @yshrsmz
Thank you for your pull request and merger.
The version of this package should be updated to 0.2.0 or 1.0.0.
See [Migrating to null safety | Dart](https://dart.dev/null-safety/migration-guide#package-version "Migrating to null safety | Dart").
Please publish the null safety version to pub.dev, then.

**Comment by yshrsmz** [comment]
I've just released v0.2.0

https://pub.dev/packages/unorm_dart

Thanks for your contribution, feel free to file a new issue if you find anything strange.
